Use explicit path in "recipe not found" exception
Replace the "Feedstock has no ..." error message with a more clear
"recipe not found" with explicit path, and a suggestion to pass
the `recipe` subdirectory.  This should help people like me, who keep
forgetting that in top feedstock directory you need to run:

    conda smithy lint recipe/

instead of just:

    conda smithy lint

and get the message:

    OSError: Feedstock has no recipe/meta.yaml

which is confusing since clearly there is a `recipe/meta.yaml`
in the current directory.  Unless you're using v1 recipes, then you get
even more confused why it tries to use a v0 recipe file.