Revert GHA template to use checkout v4.x for the time being (#2413)
* Revert GHA template to use checkout v4.x for the time being

Revert the template for GHA runners to continue using checkout v4.x
action for the time being.  The 5.x action requires NodeJS 2.4, whereas
conda-forge runners currently support up to 20.x:

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node24' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load actions/checkout/08c6903cd8c0fde910a37f88322edcfb5dd907a8/action.yml
```

Unfortunately, the update to the runners is taking longer than
anticipated, and the feedstock maintainers are forced to keep manually
reverting the changes after rerendering.  Therefore, it would be
prefereable to revert the change for now, and update the action once
the runners are ready.

Signed-off-by: Michał Górny <mgorny@quansight.com>

* Revert the change to the proxy file as well

Signed-off-by: Michał Górny <mgorny@quansight.com>

---------

Signed-off-by: Michał Górny <mgorny@quansight.com>