Support skipping `python_min` and `pip_no_build_backend` hints (#2206)
* Support skipping python_min hints

Support `hint_python_min` in `linter.skip`.  I went for a single token
for all `python_min` hints, since it seems reasonable to assume that
if one explicitly disables this, the feedstock was already inspected
for appropriate `python_min` usage.

Fixes #2170

* Support skipping pip_no_build_backend hints

Support skipping the hints about missing build backend dependency,
e.g. when the package itself is providing the build backend
(e.g. in poetry-core-feedstock).

Also requested in issue #2170.

* Fix `TypeError` when `linter:` or `skip:` keys are empty

Fix the error such as:

```
Traceback (most recent call last):
  File "/home/mgorny/miniforge3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mgorny/git/conda-smithy/conda_smithy/cli.py", line 767, in main
    args.subcommand_func(args)
  File "/home/mgorny/git/conda-smithy/conda_smithy/cli.py", line 645, in __call__
    lints, hints = linter.main(
                   ^^^^^^^^^^^^
  File "/home/mgorny/git/conda-smithy/conda_smithy/lint_recipe.py", line 733, in main
    results, hints = lintify_meta_yaml(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/git/conda-smithy/conda_smithy/lint_recipe.py", line 281, in lintify_meta_yaml
    if "lint_noarch_selectors" not in lints_to_skip:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

when `conda-forge.yml` contains an empty key, e.g.:

```
linter:
  skip:
```

Noticed this accidentally while testing the other changes.

* Add a news entry

* Don't skip "skip" tests when we expect no warnings

As suggested by @h-vetinari in https://github.com/conda-forge/conda-smithy/pull/2206#discussion_r1904288566.

---------

Co-authored-by: Matthew R. Becker <beckermr@users.noreply.github.com>